baseURL = "https://harada-kensetsu.github.io/"
languageCode = "ja"
title = "原田建設｜埼玉県入間市の地域に寄りそう工務店"
themesDir = "themes"
theme = "hugo-hero-theme"
publishDir = "public"
canonifyurls = true

[module]
  [module.hugoVersion]
    extended = true
    min = "0.55.0"

[params]
  google_analytics_id=""

  [params.homepage_meta_tags]
    meta_description = "原田建設は埼玉県入間市にある工務店です。"
    meta_og_title = "原田建設"
    meta_og_type = "website"
    meta_og_url = "https://harada-kensetsu.github.io/"
    meta_og_image = "https://raw.githubusercontent.com/JugglerX/hugo-hero-theme/master/images/tn.png"
    meta_og_description = "原田建設は埼玉県入間市にある工務店です。"
    meta_twitter_card = "summary"
    meta_twitter_site = "@"
    meta_twitter_creator = "@"

[[menu.main]]
	name = "家づくりについて"
	url = "/services/"
    weight = 1

[[menu.main]]
    name = "リフォーム"
    url = "/work/"
    weight = 2

[[menu.main]]
    name = "原田建設について"
    url = "/about/"
    weight = 3


[[menu.main]]
    name = "原田建設のこれまで"
    url = "/history/"
    weight = 3

[[menu.main]]
    name = "コンタクト"
    url = "/contact/"
    weight = 4

[permalinks]
  post = "/:year/:month/:day/:slug/"
  pages = "/:filename/"

[taxonomies]
  tag = "tags"
